---
title: "Clase 02 - DataSaurus"
output: html_notebook
---
https://jumpingrivers.github.io/datasauRus/

# Dispersión de datos

Estos datos muestran la importancia de graficar los datos para entender lo que estamos analizando. Todos los gráficos son datos con la misma media y la misma varianza y la misma cantidad de datos.

```{r}
library(tidyverse)
library(datasauRus)
library(ggplot2)
```

```{r}
dsd <- datasaurus_dozen
dsd$dataset <- factor(dsd$dataset)
str(dsd)
summary(dsd)
```


```{r}
resumen <- dsd %>% group_by(dataset) %>% reframe(n = n(), mediaX = mean(x), medianaX = median(x), sdX = sd(x), mediaY = mean(y), medianaY = median(y), sdY = sd(x))
resumen
```



```{r fig.height=15, fig.width=9}
ggplot(dsd,
       aes(x=x, y=y, colour=dataset)) +
  geom_point(alpha = 0.5) +
  theme_minimal() + # theme_minimal() theme_grey() theme_bw() theme_linedraw() theme_light() theme_dark() theme_minimal() theme_classic() theme_void()
  theme(legend.position = "none") +
  facet_wrap(~dataset, ncol=3) + 
  theme(aspect.ratio = 1)
```


