---
title: "1° Parcial - Estructuras de datos y Estadística Descriptiva"
output: html_notebook
---

ISETA. 22 de mayo de 2023

Carrera: "Tecnicatura Superior en Análisis de Sistemas".

Materia: "Estadística", correspondiente al 2do año de la carrera.

Profesor: Rafael Mac Donough.

# 1° Parcial

## Consignas:

El trabajo se entregará como un archivo R Marckdown como este. El archivo será nombrado de la siguiente manera: "ApellidoNombre-Parcial1-05-2023.Rmd"

### Elija uno de los siguientes arreglos de datos:

Cada estudiante debe elegir un arreglo diferente. Si desea trabajar con un grupo de datos que no esté incluído en esta propuesta hágalo, sólo es necesario que lo informe al profesor para que lo oriente o ayude.

-   **iris.csv** . "Edgar Anderson's Iris Data". Datos de largo y ancho de pétalos y sépalos de 3 especies del género *Iris* (*Iris setosa*, *Iris versicolor* e *Iris virginica*).
-   **diamonds.csv** . Datos de 53940 diamantes. De cada diamante se han registrado características como dimensiones, calidad de cortes y piedras y además su precio.
-   **mtcars.csv** . "Motor Trend Car Road Tests". Características de los motores y su performance para 32 modelos de autos.
-   **airquality.csv** . "New York Air Quality Measurements". Seis variables climáticas de la ciudad de New York registradas diariamente desde mayo hasta septiembre inclusive. (tiene datos faltantes).
-   **mpg.csv** . "Fuel economy data from 1999 to 2008 for 38 popular models of cars". Son datos de 238 autos de 38 modelos y sus variantes.
-   **world_bank_pop.csv** . "Population data from the world bank". Cuatro indicadores poblacionales desde 2000 hasta 2017 para todos los países del mundo. (no tiene estructura tidy).
-   **gapminder.csv** . GapMinder ([www.gapminder.org](www.gapminder.org)) es una organización con el propósito de ayudarnos a conocer cómo es el mundo. Tiene una enorme base de datos de acceso libre y en el sitiose puede interactuar gráficamente con ella. Este dataset es una pequeña extracción de su información.

### Cargue los datos

-   Cargue las librerías que necesite.
-   Cargue los datos desde un archivo .csv, haga los arreglos que necesite con su estructura. Cree un dataset tibble para trabajar con él.

### Describa los datos.

La descripción debe realizarse de 3 maneras complementarias:

#### Indicadores matemáticos:

-   Medidas de tendencia central: media, moda, mediana.
-   Medidas de Dispersión: quantiles, valores extremos, Desvío Estándar y varianza.

#### Gráficos y tablas:

-   Histogramas, densidad, frecuencia acumulada, etc.
-   BoxPlot, violín.
-   Dispersión (para las variables cuantitativas), líneas, barras o columnas.
-   Puede organizar la información mostrándola en tablas. Puede hacerlas a mano en el formato R Marckdown o usar las funciones de tabulación como table() o prop.table().

#### Texto:

-   Explicaciones breves y concisas de lo hecho.
-   Descripción breve de los aspectos a destacar de las estadísticas previas.
-   Breve interpretación del análisis.

## Recomendaciones

-   Organice el trabajo como le resulte más claro.
-   No se obligue a realizar todo lo que se pide.
-   Pida ayuda cuando lo necesite (puede consultar a su profesor, a compañeros, en internet o a quién lo crea conveniente). Pedir ayuda no es trampa!
-   Anímese a ir más allá de lo estrictamente pedido.

```{r}

```
