---
title: "Probabilidad - Montecarlo - El dilema de Perseo"
output: html_notebook
---

Perseo debe rescatar a la bella Andrómeda prisionera en una caverna cuya entrada está bloqueada con rocas. El probglema es que hay tres cavernas idénticas; una de ellas aloja a Andrómeda y en cada una de las otras dos se oculta una górona, monstruo legendario que petrifica a los intrusos con sólo una mirada. Perseo consulta a Pegasa - la urraca mítica - quién manifiesta saber en qué caverna se encuentra Andrómeda, pero no le es permitido revelar el secreto so pena de terrible castigo por parte de los dioses; sin embargo puede ayudar a Perseo. Éste dice que, a su parecer, Andrómeda está en la caverna del centro; Pegasa informa entonces que en la de la izquierda hay una górgona. Aquí se presenta el dilema, ¿aumentan las posibilidades de Perseo de acertar con la caverna correcta si toma en cuenta la revelación de Pegasa y cambia su decisión a la?

duda y elige finalmente la caverna del centro. Pegasa, la urraca mítica, interviene. No puede salvar a Perseo pero sí ayudarlo. Le dice que en la caverna de la izquierda hay una gorgona. He aquí el dilema. ¿Le conviene a Perseo cambiar su elección, o no? Esta mítica diyuntiva puede, en realidad, ser más frecuente que lo que uno supone. El autor discute el dilema y nos provee de una respuesta al mismo.

```{r}

```


